In [1]:
# load the libaray
import numpy as np

In [2]:
# print the version and conficuration
print(np.__version__)
np.show_config()

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Dell/anaconda3/envs/ml_projects\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Dell/anaconda3/envs/ml_projects\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Dell/anaconda3/envs/ml_projects\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Dell/anaconda3/envs/ml_projects\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Dell/anaconda3/envs/ml_projects\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Dell/anaconda3/envs/ml_projects\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Dell/anaconda3/envs/ml_projects\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]

In [3]:
# create null vector of size 10
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
# Create a null vector of size 10 but the fifth value which is 1
arr = np.zeros(10)
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [6]:
# Create a vector with values ranging from 10 to 49
print(np.arange(10, 50))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [7]:
# Reverse a vector (first element becomes last)
arr = np.arange(1,10)
arr= arr[::-1]
arr

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [9]:
# Create a 3x3 matrix with values ranging from 0 to 8
print(np.arange(0,9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
# Find indices of nonzero elements from [1,2,0,0,4,0]
print(np.nonzero([1,2,0,0,5,0,7]))

(array([0, 1, 4, 6], dtype=int64),)


In [11]:
# Create a 3x3 identity matrix
print(np.eye(3,3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
# Create a 3x3x3 array with random values
np.random.random((3,3,3))

array([[[0.15951857, 0.0925233 , 0.85740291],
        [0.68865386, 0.03136119, 0.42082792],
        [0.58039975, 0.81968496, 0.19770542]],

       [[0.19822203, 0.30547392, 0.65107618],
        [0.21237955, 0.8570474 , 0.83335363],
        [0.89571245, 0.99319207, 0.63005633]],

       [[0.95815843, 0.90767634, 0.453293  ],
        [0.10401973, 0.92539777, 0.40493375],
        [0.6281458 , 0.73593163, 0.85281111]]])

In [19]:
# Create a 10x10 array with random values and find the minimum and maximum values
arr = np.random.random((10,10))
arr_min, arr_max = np.min(arr), np.max(arr)
print(arr_min, arr_max)

0.001269594597435364 0.9948931418942578


In [20]:
# Create a random vector of size 30 and find the mean value
arr = np.random.random((10))
np.mean(arr)

0.5563680765042224

In [26]:
# Create a 2d array with 1 on the border and 0 inside
arr = np.ones((4,4))
arr[1:-1, 1:-1] = 0
arr

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [27]:
# What is the result of the following expression?

0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

False

In [28]:
# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [29]:
# Create a 8x8 matrix and fill it with a checkerboard pattern
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [30]:
# Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [31]:
# Create a checkerboard 8x8 matrix using the tile function
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [32]:
# Normalize a 5x5 random matrix
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.4054333  0.52885102 0.04890972 0.21706843 0.57750071]
 [0.97758788 1.         0.16882672 0.6227831  0.59347286]
 [0.39128492 0.79454816 0.1198316  0.0189666  0.7986265 ]
 [0.         0.06783093 0.91644919 0.52020182 0.45711503]
 [0.10460533 0.55698981 0.2924665  0.51601846 0.69591602]]


In [34]:
# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
z = np.dot(np.ones((5,3)), np.ones((3,2)))
z

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [37]:
# Given a 1D array, negate all elements which are between 3 and 8, in place
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1

Z

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

In [38]:
# What is the output of the following script?

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [40]:
# Extract the integer part of a random array using 5 different methods

Z = np.random.uniform(0,10,10)
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[2. 0. 8. 7. 4. 0. 2. 7. 2. 7.]
[2. 0. 8. 7. 4. 0. 2. 7. 2. 7.]
[2. 0. 8. 7. 4. 0. 2. 7. 2. 7.]
[2 0 8 7 4 0 2 7 2 7]
[2. 0. 8. 7. 4. 0. 2. 7. 2. 7.]


In [41]:
# Create a 5x5 matrix with row values ranging from 0 to 4

Z = np.zeros((5,5))
Z+=np.arange(5)
Z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [44]:
# Consider a generator function that generates 10 integers and use it to build an array
def generate():
    for x in xrange(10):
        yield x
    Z = np.fromiter(generate(),dtype=float,count=-1)

print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [45]:
# Create a vector of size 10 with values ranging from 0 to 1, both excluded
Z = np.linspace(0,1,12,endpoint=True)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [47]:
# Create a random vector of size 10 and sort it
Z = np.random.random(10)
z.sort()
z

array([-10,  -9,  -8,   0,   1,   2,   3,   4,   5,   6,   7])

In [48]:
# How to sum a small array faster than np.sum?
Z = np.arange(10)
np.add.reduce(Z)

45

In [49]:
# Consider two random array A anb B, check if they are equal

A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


In [50]:
# Make an array immutable (readonly)
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only