In [187]:
# libraries for numerical
import pandas as pd  
import numpy as np

# libraries for visualization
import matplotlib.pyplot as plt  
import seaborn as sns

# libraries for machine learning
from sklearn.model_selection import train_test_split 
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import mean_squared_error, r2_score, f1_score
from sklearn import metrics

# to plot the diagrams within the cells
%matplotlib inline

In [189]:
train_data = pd.read_csv("https://raw.githubusercontent.com/dphi-official/Datasets/master/clamp/train_set_label.csv")
test_data = pd.read_csv('https://raw.githubusercontent.com/dphi-official/Datasets/master/clamp/test_set_label.csv')

In [190]:
train_data.describe()

e_magic        e_cblp         e_cp  e_crlc    e_cparhdr   e_minalloc  \
count   3888.0   3888.000000  3888.000000  3888.0  3888.000000  3888.000000   
mean   23117.0    148.252058     2.947016     0.0     3.967593     2.120885   
std        0.0    591.610421     2.291419     0.0     0.357188    65.785975   
min    23117.0      0.000000     0.000000     0.0     0.000000     0.000000   
25%    23117.0    144.000000     3.000000     0.0     4.000000     0.000000   
50%    23117.0    144.000000     3.000000     0.0     4.000000     0.000000   
75%    23117.0    144.000000     3.000000     0.0     4.000000     0.000000   
max    23117.0  37008.000000   144.000000     0.0     4.000000  4096.000000   

         e_maxalloc          e_ss          e_sp       e_csum  ...  \
count   3888.000000   3888.000000   3888.000000  3888.000000  ...   
mean   65110.442901     16.851852    199.741255     0.001029  ...   
std     5195.740601   1050.777490   1048.231580     0.039275  ...   
min        0.000000      0.000000      0.000000     0.000000  ...   
25%    65535.000000      0.000000    184.000000     0.000000  ...   
50%    65535.000000      0.000000    184.000000     0.000000  ...   
75%    65535.000000      0.000000    184.000000     0.000000  ...   
max    65535.000000  65520.000000  65534.000000     2.000000  ...   

           CheckSum    Subsystem  DllCharacteristics  SizeOfStackReserve  \
count  3.888000e+03  3888.000000         3888.000000        3.888000e+03   
mean   1.785479e+06     2.132202         9489.058899        2.008231e+06   
std    6.906378e+07     0.474741        14841.770405        4.682014e+06   
min    0.000000e+00     0.000000            0.000000        0.000000e+00   
25%    0.000000e+00     2.000000            0.000000        1.048576e+06   
50%    7.894150e+04     2.000000            0.000000        1.048576e+06   
75%    2.128122e+05     2.000000        32768.000000        1.048576e+06   
max    4.294967e+09    16.000000        37184.000000        3.355443e+07   

       SizeOfStackCommit  SizeOfHeapReserve  SizeOfHeapCommit   LoaderFlags  \
count       3.888000e+03       3.888000e+03       3888.000000  3.888000e+03   
mean        1.072442e+04       2.065907e+06       5694.156379  3.151187e+04   
std         8.256807e+04       4.397444e+06       6510.114435  1.342464e+06   
min         0.000000e+00       0.000000e+00          0.000000  0.000000e+00   
25%         4.096000e+03       1.048576e+06       4096.000000  0.000000e+00   
50%         4.096000e+03       1.048576e+06       4096.000000  0.000000e+00   
75%         8.192000e+03       1.048576e+06       4096.000000  0.000000e+00   
max         2.097152e+06       3.355443e+07      65536.000000  6.342951e+07   

       NumberOfRvaAndSizes        class  
count          3888.000000  3888.000000  
mean             15.972737     0.517490  
std               0.648187     0.499758  
min               0.000000     0.000000  
25%              16.000000     0.000000  
50%              16.000000     1.000000  
75%              16.000000     1.000000  
max              16.000000     1.000000  

[8 rows x 56 columns]

In [191]:
train_data.shape

(3888, 56)

In [192]:
train_data.isnull().sum()

e_magic                           0
e_cblp                            0
e_cp                              0
e_crlc                            0
e_cparhdr                         0
e_minalloc                        0
e_maxalloc                        0
e_ss                              0
e_sp                              0
e_csum                            0
e_ip                              0
e_cs                              0
e_lfarlc                          0
e_ovno                            0
e_res                          3888
e_oemid                           0
e_oeminfo                         0
e_res2                         3888
e_lfanew                          0
Machine                           0
NumberOfSections                  0
CreationYear                      0
PointerToSymbolTable              0
NumberOfSymbols                   0
SizeOfOptionalHeader              0
Characteristics                   0
Magic                             0
MajorLinkerVersion          

In [193]:
# drop the optional columns
#train_data = train_data[["e_magic", "e_cblp", "e_cp","e_crlc","e_cparhdr","e_minalloc","e_maxalloc","e_ss","e_sp",
#                        "e_csum","e_ip","e_cs","e_lfarlc","e_ovno","e_res","e_oemid","e_oeminfo","e_res2","e_lfanew",
#                        "Machine","NumberOfSections","CreationYear","PointerToSymbolTable", "NumberOfSymbols",
#                        "SizeOfOptionalHeader","Characteristics", "class"]]
#train_data.shape

In [194]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3888 entries, 0 to 3887
Data columns (total 56 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   e_magic                      3888 non-null   int64  
 1   e_cblp                       3888 non-null   int64  
 2   e_cp                         3888 non-null   int64  
 3   e_crlc                       3888 non-null   int64  
 4   e_cparhdr                    3888 non-null   int64  
 5   e_minalloc                   3888 non-null   int64  
 6   e_maxalloc                   3888 non-null   int64  
 7   e_ss                         3888 non-null   int64  
 8   e_sp                         3888 non-null   int64  
 9   e_csum                       3888 non-null   int64  
 10  e_ip                         3888 non-null   int64  
 11  e_cs                         3888 non-null   int64  
 12  e_lfarlc                     3888 non-null   int64  
 13  e_ovno            

In [195]:
train_data.drop(['e_res', 'e_res2'], axis=1, inplace=True)

In [196]:
train_data.head()

e_magic  e_cblp  e_cp  e_crlc  e_cparhdr  e_minalloc  e_maxalloc  e_ss  \
0    23117     144     3       0          4           0       65535     0   
1    23117     144     3       0          4           0       65535     0   
2    23117     144     3       0          4           0       65535     0   
3    23117     144     3       0          4           0       65535     0   
4    23117     144     3       0          4           0       65535     0   

   e_sp  e_csum  ...  CheckSum  Subsystem  DllCharacteristics  \
0   184       0  ...    115397          2               33792   
1   184       0  ...         0          2                   0   
2   184       0  ...         0          2                   0   
3   184       0  ...    142244          2               33088   
4   184       0  ...     60601          2                1024   

   SizeOfStackReserve  SizeOfStackCommit  SizeOfHeapReserve  SizeOfHeapCommit  \
0             1048576               4096            1048576              4096   
1            10485760              40960            6291456             16384   
2             1048576               4096            1048576              4096   
3              262144               8192            1048576              4096   
4             1048576               4096            1048576              4096   

   LoaderFlags  NumberOfRvaAndSizes  class  
0            0                   16      1  
1            0                   16      1  
2            0                   16      0  
3            0                   16      0  
4            0                   16      0  

[5 rows x 54 columns]

In [197]:
train_data.describe()

e_magic        e_cblp         e_cp  e_crlc    e_cparhdr   e_minalloc  \
count   3888.0   3888.000000  3888.000000  3888.0  3888.000000  3888.000000   
mean   23117.0    148.252058     2.947016     0.0     3.967593     2.120885   
std        0.0    591.610421     2.291419     0.0     0.357188    65.785975   
min    23117.0      0.000000     0.000000     0.0     0.000000     0.000000   
25%    23117.0    144.000000     3.000000     0.0     4.000000     0.000000   
50%    23117.0    144.000000     3.000000     0.0     4.000000     0.000000   
75%    23117.0    144.000000     3.000000     0.0     4.000000     0.000000   
max    23117.0  37008.000000   144.000000     0.0     4.000000  4096.000000   

         e_maxalloc          e_ss          e_sp       e_csum  ...  \
count   3888.000000   3888.000000   3888.000000  3888.000000  ...   
mean   65110.442901     16.851852    199.741255     0.001029  ...   
std     5195.740601   1050.777490   1048.231580     0.039275  ...   
min        0.000000      0.000000      0.000000     0.000000  ...   
25%    65535.000000      0.000000    184.000000     0.000000  ...   
50%    65535.000000      0.000000    184.000000     0.000000  ...   
75%    65535.000000      0.000000    184.000000     0.000000  ...   
max    65535.000000  65520.000000  65534.000000     2.000000  ...   

           CheckSum    Subsystem  DllCharacteristics  SizeOfStackReserve  \
count  3.888000e+03  3888.000000         3888.000000        3.888000e+03   
mean   1.785479e+06     2.132202         9489.058899        2.008231e+06   
std    6.906378e+07     0.474741        14841.770405        4.682014e+06   
min    0.000000e+00     0.000000            0.000000        0.000000e+00   
25%    0.000000e+00     2.000000            0.000000        1.048576e+06   
50%    7.894150e+04     2.000000            0.000000        1.048576e+06   
75%    2.128122e+05     2.000000        32768.000000        1.048576e+06   
max    4.294967e+09    16.000000        37184.000000        3.355443e+07   

       SizeOfStackCommit  SizeOfHeapReserve  SizeOfHeapCommit   LoaderFlags  \
count       3.888000e+03       3.888000e+03       3888.000000  3.888000e+03   
mean        1.072442e+04       2.065907e+06       5694.156379  3.151187e+04   
std         8.256807e+04       4.397444e+06       6510.114435  1.342464e+06   
min         0.000000e+00       0.000000e+00          0.000000  0.000000e+00   
25%         4.096000e+03       1.048576e+06       4096.000000  0.000000e+00   
50%         4.096000e+03       1.048576e+06       4096.000000  0.000000e+00   
75%         8.192000e+03       1.048576e+06       4096.000000  0.000000e+00   
max         2.097152e+06       3.355443e+07      65536.000000  6.342951e+07   

       NumberOfRvaAndSizes        class  
count          3888.000000  3888.000000  
mean             15.972737     0.517490  
std               0.648187     0.499758  
min               0.000000     0.000000  
25%              16.000000     0.000000  
50%              16.000000     1.000000  
75%              16.000000     1.000000  
max              16.000000     1.000000  

[8 rows x 54 columns]

In [198]:
X = train_data.drop('class', axis=1)
y = train_data['class']

In [199]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2, random_state = 9)

In [141]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler() 
x_train = scaler.fit_transform(X_train) 
x_test = scaler.transform(X_test)

In [200]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(criterion='gini', n_estimators=27)
model.fit(X_train, y_train)
prediction = model.predict(X_test)

In [201]:
prediction

array([0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,

In [202]:
model.score(X_test, y_test)

0.9832904884318766

In [203]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(y_test,prediction))
print(accuracy_score(y_test,prediction))
print(classification_report(y_test,prediction))

[[369  10]
 [  3 396]]
0.9832904884318766
              precision    recall  f1-score   support

           0       0.99      0.97      0.98       379
           1       0.98      0.99      0.98       399

    accuracy                           0.98       778
   macro avg       0.98      0.98      0.98       778
weighted avg       0.98      0.98      0.98       778



In [204]:
### Manual Hyperparameter Tuning
model=RandomForestClassifier(n_estimators=300,criterion='entropy',
                             max_features='sqrt',min_samples_leaf=10,random_state=100).fit(X_train,y_train)
predictions=model.predict(X_test)
print(confusion_matrix(y_test,predictions))
print(accuracy_score(y_test,predictions))
print(classification_report(y_test,predictions))

[[367  12]
 [  6 393]]
0.9768637532133676
              precision    recall  f1-score   support

           0       0.98      0.97      0.98       379
           1       0.97      0.98      0.98       399

    accuracy                           0.98       778
   macro avg       0.98      0.98      0.98       778
weighted avg       0.98      0.98      0.98       778



In [205]:
test_data.drop(['e_res', 'e_res2'], axis=1, inplace=True)

In [206]:
y_pred = model.predict(test_data)
y_pred

array([1, 1, 0, ..., 0, 0, 1], dtype=int64)

In [207]:
res_rfc = pd.DataFrame(y_pred) #target is nothing but the final predictions of your model on input features of your new unseen test data
#res.index = test_data.index # its important for comparison. Here "test_new" is your new test dataset
res_rfc.columns = ["prediction"]
res_rfc.to_csv("submission_rfc.csv", index=False)      # the csv file will be saved locally on the same location where this notebook is located.

In [150]:
import numpy as np
from sklearn.model_selection import RandomizedSearchCV
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt','log2']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 1000,10)]
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10,14]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4,6,8]
# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
              'criterion':['entropy','gini']}
print(random_grid)

{'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000], 'max_features': ['auto', 'sqrt', 'log2'], 'max_depth': [10, 120, 230, 340, 450, 560, 670, 780, 890, 1000], 'min_samples_split': [2, 5, 10, 14], 'min_samples_leaf': [1, 2, 4, 6, 8], 'criterion': ['entropy', 'gini']}


In [151]:
rf=RandomForestClassifier()
rf_randomcv=RandomizedSearchCV(estimator=rf,param_distributions=random_grid,n_iter=100,cv=3,verbose=2,
                               random_state=100,n_jobs=-1)
### fit the randomized model
rf_randomcv.fit(X_train,y_train)

Fitting 3 folds for each of 100 candidates, totalling 300 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:   56.7s
[Parallel(n_jobs=-1)]: Done 154 tasks      | elapsed:  4.4min
[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:  8.6min finished


RandomizedSearchCV(cv=3, estimator=RandomForestClassifier(), n_iter=100,
                   n_jobs=-1,
                   param_distributions={'criterion': ['entropy', 'gini'],
                                        'max_depth': [10, 120, 230, 340, 450,
                                                      560, 670, 780, 890,
                                                      1000],
                                        'max_features': ['auto', 'sqrt',
                                                         'log2'],
                                        'min_samples_leaf': [1, 2, 4, 6, 8],
                                        'min_samples_split': [2, 5, 10, 14],
                                        'n_estimators': [200, 400, 600, 800,
                                                         1000, 1200, 1400, 1600,
                                                         1800, 2000]},
                   random_state=100, verbose=2)

In [152]:
 rf_randomcv.best_params_

{'n_estimators': 600,
 'min_samples_split': 2,
 'min_samples_leaf': 1,
 'max_features': 'sqrt',
 'max_depth': 890,
 'criterion': 'gini'}

In [153]:
rf_randomcv

RandomizedSearchCV(cv=3, estimator=RandomForestClassifier(), n_iter=100,
                   n_jobs=-1,
                   param_distributions={'criterion': ['entropy', 'gini'],
                                        'max_depth': [10, 120, 230, 340, 450,
                                                      560, 670, 780, 890,
                                                      1000],
                                        'max_features': ['auto', 'sqrt',
                                                         'log2'],
                                        'min_samples_leaf': [1, 2, 4, 6, 8],
                                        'min_samples_split': [2, 5, 10, 14],
                                        'n_estimators': [200, 400, 600, 800,
                                                         1000, 1200, 1400, 1600,
                                                         1800, 2000]},
                   random_state=100, verbose=2)

In [154]:
best_random_grid=rf_randomcv.best_estimator_

In [155]:
best_random_grid

RandomForestClassifier(max_depth=890, max_features='sqrt', n_estimators=600)

In [156]:
from sklearn.metrics import accuracy_score
y_pred=best_random_grid.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print("Accuracy Score {}".format(accuracy_score(y_test,y_pred)))
print("Classification report: {}".format(classification_report(y_test,y_pred)))

[[371   8]
 [  4 395]]
Accuracy Score 0.9845758354755784
Classification report:               precision    recall  f1-score   support

           0       0.99      0.98      0.98       379
           1       0.98      0.99      0.99       399

    accuracy                           0.98       778
   macro avg       0.98      0.98      0.98       778
weighted avg       0.98      0.98      0.98       778



In [157]:
best_random_grid.score(X_test, y_test)

0.9845758354755784

In [158]:
y_pred = best_random_grid.predict(test_data)
y_pred

array([1, 1, 0, ..., 0, 0, 1], dtype=int64)

In [159]:
res = pd.DataFrame(y_pred) #target is nothing but the final predictions of your model on input features of your new unseen test data
#res.index = test_data.index # its important for comparison. Here "test_new" is your new test dataset
res.columns = ["prediction"]
res.to_csv("submission_rfc_rgsc.csv", index=False)      # the csv file will be saved locally on the same location where this notebook is located.

In [160]:
from sklearn.model_selection import GridSearchCV

In [208]:
param_grid = {
    'criterion': [rf_randomcv.best_params_['criterion']],
    'max_depth': [rf_randomcv.best_params_['max_depth']],
    'max_features': [rf_randomcv.best_params_['max_features']],
    'min_samples_leaf': [rf_randomcv.best_params_['min_samples_leaf'], 
                         rf_randomcv.best_params_['min_samples_leaf']+2, 
                         rf_randomcv.best_params_['min_samples_leaf'] + 4],
    'min_samples_split': [rf_randomcv.best_params_['min_samples_split'] - 2,
                          rf_randomcv.best_params_['min_samples_split'] - 1,
                          rf_randomcv.best_params_['min_samples_split'], 
                          rf_randomcv.best_params_['min_samples_split'] +1,
                          rf_randomcv.best_params_['min_samples_split'] + 2],
    'n_estimators': [rf_randomcv.best_params_['n_estimators'] - 200, rf_randomcv.best_params_['n_estimators'] - 100, 
                     rf_randomcv.best_params_['n_estimators'], 
                     rf_randomcv.best_params_['n_estimators'] + 100, rf_randomcv.best_params_['n_estimators'] + 200]
}

print(param_grid)

{'criterion': ['gini'], 'max_depth': [890], 'max_features': ['sqrt'], 'min_samples_leaf': [1, 3, 5], 'min_samples_split': [0, 1, 2, 3, 4], 'n_estimators': [400, 500, 600, 700, 800]}


In [209]:
#### Fit the grid_search to the data
rf=RandomForestClassifier()
grid_search=GridSearchCV(estimator=rf,param_grid=param_grid,cv=10,n_jobs=-1,verbose=2)
grid_search.fit(X_train,y_train)

Fitting 10 folds for each of 75 candidates, totalling 750 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:   10.4s
[Parallel(n_jobs=-1)]: Done 154 tasks      | elapsed:  2.0min
[Parallel(n_jobs=-1)]: Done 357 tasks      | elapsed:  5.1min
[Parallel(n_jobs=-1)]: Done 640 tasks      | elapsed:  9.9min
[Parallel(n_jobs=-1)]: Done 750 out of 750 | elapsed: 12.6min finished


GridSearchCV(cv=10, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini'], 'max_depth': [890],
                         'max_features': ['sqrt'],
                         'min_samples_leaf': [1, 3, 5],
                         'min_samples_split': [0, 1, 2, 3, 4],
                         'n_estimators': [400, 500, 600, 700, 800]},
             verbose=2)

In [210]:
grid_search.best_estimator_

RandomForestClassifier(max_depth=890, max_features='sqrt', n_estimators=700)

In [211]:
best_grid=grid_search.best_estimator_

In [212]:
best_grid

RandomForestClassifier(max_depth=890, max_features='sqrt', n_estimators=700)

In [213]:
y_pred=best_grid.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print("Accuracy Score {}".format(accuracy_score(y_test,y_pred)))
print("Classification report: {}".format(classification_report(y_test,y_pred)))

[[371   8]
 [  3 396]]
Accuracy Score 0.9858611825192802
Classification report:               precision    recall  f1-score   support

           0       0.99      0.98      0.99       379
           1       0.98      0.99      0.99       399

    accuracy                           0.99       778
   macro avg       0.99      0.99      0.99       778
weighted avg       0.99      0.99      0.99       778



In [214]:
best_grid.score(X_test, y_test)

0.9858611825192802

In [215]:
y_pred = best_grid.predict(test_data)
y_pred

array([1, 1, 0, ..., 0, 0, 1], dtype=int64)

In [216]:
res_gscv = pd.DataFrame(y_pred) #target is nothing but the final predictions of your model on input features of your new unseen test data
#res.index = test_data.index # its important for comparison. Here "test_new" is your new test dataset
res_gscv.columns = ["prediction"]
res_gscv.to_csv("submission_rfc_gscv.csv", index=False)      # the csv file will be saved locally on the same location where this notebook is located.

In [217]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import Perceptron
from sklearn.linear_model import SGDClassifier

In [218]:
### k -Nearest Neighbors
clf_kn = KNeighborsClassifier(n_neighbors = 3)
clf_kn.fit(X_train, y_train)
y_pred_knn = clf_kn.predict(X_test)
acc_knn = round(clf_kn.score(X_train, y_train) * 100, 2)
print ("Train Accuracy: " + str(acc_knn) + '%')

Train Accuracy: 96.72%


In [219]:
res_knn = pd.DataFrame(y_pred) #target is nothing but the final predictions of your model on input features of your new unseen test data
#res.index = test_data.index # its important for comparison. Here "test_new" is your new test dataset
res_knn.columns = ["prediction"]
res_knn.to_csv("submission_rfc_res_knn.csv", index=False)# the csv file will be saved locally on the same location where this notebook is located.

In [220]:
### Support Vector Machine

clf = SVC()
clf.fit(X_train, y_train)
y_pred_svc = clf.predict(X_test)
acc_svc = round(clf.score(X_train, y_train) * 100, 2)
print ("Train Accuracy: " + str(acc_svc) + '%')

Train Accuracy: 74.37%


In [221]:
from sklearn.ensemble import GradientBoostingClassifier

In [222]:
reg = GradientBoostingClassifier(random_state=9)
reg.fit(X_train, y_train)

GradientBoostingClassifier(random_state=9)

In [223]:
reg.score(X_test, y_test)

0.9768637532133676

In [183]:
y_pred=reg.predict(X_test)
y_pred

array([0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,

In [184]:
y_pred = reg.predict(test_data)
y_pred

array([1, 1, 0, ..., 0, 0, 1], dtype=int64)

In [185]:
res_gb = pd.DataFrame(y_pred) #target is nothing but the final predictions of your model on input features of your new unseen test data
#res.index = test_data.index # its important for comparison. Here "test_new" is your new test dataset
res_gb.columns = ["prediction"]
res_gb.to_csv("submission_gb.csv", index=False)# the csv file will be saved locally on the same location where this notebook is located.